#!/usr/bin/env bash
# Displays "Best School" 10 times, but but for the 9th iteration, displays Best School and then Hi on a new line.

counter=10
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  counter=$((counter+1))
done
