#!/usr/bin/env bash

# Install nginx if not already installed
if ! command -v nginx &>/dev/null; then
	    apt-get update
	        apt-get install -y nginx
fi

# Change ownership of Nginx directories to nginx user
chown -R nginx:nginx /var/log/nginx /var/lib/nginx

# Modify Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/^user .*;$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/^listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
systemctl restart nginx

